alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../..'
alias bash='SHELL=bash bash'
alias dotfiles='cd $DOTFILES'
alias dotfile_colors="set | egrep '^COLOR_\w*' | sort " # lists all the colors
alias ga='git add -p'
alias gb='git br'
alias gci='git ci'
alias gd='git diff'
alias gh='git hist -10'
alias gg='git grep --line-number --ignore-case --extended-regexp --color=always --break --heading'
alias gm='git merge --no-edit --no-ff'
alias gp='git pull'
alias gr='git review'
alias gs='git status'
alias less='less -R'
alias ll='ls -alFh'
alias ls='ls --color=auto'
alias ssh='ssh -A'
alias psg='ps -ef | grep'
alias zsh='SHELL=zsh zsh'
