alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../..'
alias colors="set | egrep '^COLOR_\w*' | sort " # lists all the colors
alias dot='cd $DOTFILES'
alias ga='git add -p'
alias gb='git br'
alias gci='git ci'
alias gd='git diff'
alias gg='git grep --line-number --ignore-case --extended-regexp --color=always --break --heading'
alias ggrep='grep -irn'
alias gm='git merge --no-edit --no-ff'
alias gp='git pull'
alias gs='git status'
alias less='less -R'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias psg='ps -ef | grep'
